### ISSUE TITLE
A way to filter color codes away from in-game command responses

### ISSUE THREAD

**Issue by HeavenCrafter** [janispritzkau/rcon-client#10]
I'm currently building an RCON function onto my Discord.js bot but only one issue with that is, color codes just look like normal text which can be an eyesore sometimes. Even console responses can look quite annoying at times as well so was kinda wondering, any possible way around this?

**Comment by HeavenCrafter** [comment]
Reference image
![image](https://user-images.githubusercontent.com/22242534/90923557-7ae2ed00-e420-11ea-9504-8eec17b0a942.png)

**Comment by janispritzkau** [comment]
It's not something I would implement into this library. But a simple regular expression should do the trick: `text.replace(/§./g, "")`
