### ISSUE TITLE
How to use this with Javascript?

### ISSUE THREAD

**Issue by The-UnknownUser** [janispritzkau/rcon-client#15]
Hello, I found this package, and is genial, but, I don't know how to use this in Javascript and not Typescript, is a node package, so is possible, or not?

**Comment by janispritzkau** [comment]
You can use it just like shown in the example in the README. Since you're probably not using ES modules then you have to use `require` instead of the import.

**Comment by janispritzkau** [comment]
Here is an example of how you import the library without TypeScript or ES modules:

```js
const { Rcon } = require("rcon-client")
```
