### ISSUE TITLE
Error when using in combination with javascript.

### ISSUE THREAD

**Issue by Hyperbuilder** [janispritzkau/rcon-client#17]
When i start the bot i get this:
TypeError: Rcon is not a constructor

I have a file called Create.js:
const Rcon = require('rcon-client')
const rcon = new Rcon({
            host: config.ip,
            port: 25575,
            password: config.RconPass
        })
        
What is going wrong and how could i fix it?

**Comment by Hyperbuilder** [comment]
as you said in issue #15:
Use require
I did use it correctly didnt i?

**Comment by janispritzkau** [comment]
You have to import it like this:

```javascript
const { Rcon } = require("rcon-client")
// or this
const Rcon = require("rcon-client").Rcon
```
