### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TheSpartaPT** [janispritzkau/rcon-client#2]
Is this only for Minecraft or does it work with any game?
You seem to advertise it as being only for Minecraft, but the name of the package kind of implies that this is a client for the protocol as a whole.
So yeah I'm confused and i'd like an answer so I don't waste my time trying to use it and failing.

**Comment by janispritzkau** [comment]
Hi, I did make the package for Minecraft. Since I wasn't sure if it works with other games I didn't advertise it as such. I'll be looking into the differences of the Minecraft and Source RCON protocol. Maybe there's an easy fix to make it work with both.

**Comment by janispritzkau** [comment]
One major difference is that some game server use UDP instead of TCP for the protocol.

**Comment by TheSpartaPT** [comment]
GoldSource (CS 1.6, HL, etc.) used/uses UDP
The newer Source (CS Source, CS GO, HL 2, etc.) uses TCP, so I think it's pretty much the same as Minecraft which seems to be only an implementation of the Source Rcon, but I guess I can test it out and give you some feedback

**Comment by TheSpartaPT** [comment]
![image](https://user-images.githubusercontent.com/8343238/65640618-b0017800-dfe2-11e9-9e6e-be87df96017f.png)

Tested it with a Squad server
seems to work fine but the `end` event never seemed to be fired, everything else seems to work

**Comment by janispritzkau** [comment]
I think that TCP reset should be handled better. At the moment it only fires the `error` event, but not `end`. The `close` event of the socket is probably better suited, as it also fires when the connection is not properly closed.

**Comment by Hornwitser** [comment]
This implementation doesn't quite follow the RCON protocol as documented on the [Valve Developer Pages](https://developer.valvesoftware.com/wiki/Source_RCON_Protocol).  The most important differences are
- The maximum packet size is not adhered to.  Packet sizes arbitrarily longer than the maximum specified of 4096 can both be received and sent.  Factorio allows this, and Clusterio depends on this.
- Multi-packet responses are not handled.  The RCON document says that responses longer than 4096 bytes are split up into however many 4096 byte long packets are needed.  But alas, they messed it up and there's no reliable way to detect the end of a mult-packet response.  Factorio doesn't send multi-packet responses, the response is in one packet no matter how big and this splitting the response into multiple "packets" doesn't make any sense over tcp.
- There's a workaround for detecting the end of a multi-packet responses that this client doesn't do.  If you try to use this workaround with Factorio the connection is dropped so for example you can't use the python-valve rcon client with Factorio for this reason.
- Commands are encoded in UTF-8 and responses are decoded as UTF-8.  This is what both Minecraft and Factorio expects, but the protocol document clearly says it's a "Null-terminated ASCII string" whatever that means.

Further more, out of order results of commands is correctly handled (Factorio does this) something the Valve document says can't happen.

Honestly this whole protocol feels like it was hastily cobbled together a late afternoon by a drunk developer.  It's got a 32-bit payload length field that cannot contain a length greater than than 12 bits, it's got space for 4 billion different payload types yet it still recycles payload IDs and fails to mark the end of multi packet responses.  I'm appalled than games actually use this trash.

**Comment by janispritzkau** [comment]
I'm gonna close this issue. And to answer the question I guess this library is more targeted toward Minecraft servers as that's what I made it for but any small changes to make it more compatible with other games are welcome.
