### ISSUE TITLE
Not working for Chivalry Medieval Warfare 

### ISSUE THREAD

**Issue by avi312singh** [janispritzkau/rcon-client#20]
Title is pretty self explanatory

I took some time to debug the code and here is what happened... Couldn't authenticate

![image](https://user-images.githubusercontent.com/5769090/122660803-3c22de00-d17c-11eb-8612-20cebef4962b.png)

Does it have anything to do with the fact chivalry has this documentation for the Rcon Protocol: [RCON Documentation](https://tornbannerjira.atlassian.net/wiki/spaces/CHIVCOM/pages/9175118/RCon+Protocol)

Would this be a problem?

```
const { Rcon } = require('rcon-client')

async function main() {
    const rcon = new Rcon({
        host: "79.98.25.135",
        port: 25575,
        password: "xxxxxx"
    })

    rcon.on("connect", () => console.log("connected"))
    rcon.on("authenticated", () => console.log("authenticated"))
    rcon.on("end", () => console.log("end"))

    await rcon.connect()

    console.log('connected')
    // console.log(await rcon.send("/list"))

    // await Promise.all([...Array(10)].map((_, i) => rcon.send(`/say ${i}`)))

    rcon.end()
}

main().catch(console.error)
```

`Error: connect ETIMEDOUT 79.98.25.135:25575`

**Comment by janispritzkau** [comment]
Sorry, I never created it to work with non-Minecraft servers. There was a comment in the README, though.
