### ISSUE TITLE
Raw Buffer as input and output

### ISSUE THREAD

**Issue by Hornwitser** [janispritzkau/rcon-client#3]
This is a feature request that I think may be useful in certain limited circumstances, and should be simple to implement.  I want to be able to send a Buffer of bytes instead of a string, and I want to receive back a Buffer of bytes as the response instead of a string.  Effectively bypassing the encoding and decoding as UTF-8.

Since Factorio doesn't care much about what bytes you send it, and it allows you to send any bytes as a response to an Rcon command (except for nul bytes) this feature would be useful for making a compact binary encoding to exchange data between Factorio and an external program.

**Comment by janispritzkau** [comment]
I've implemented this with a seperate `sendRaw(buffer)` method.
