### ISSUE TITLE
Crash when there is no endpoint

### ISSUE THREAD

**Issue by mindforger** [janispritzkau/rcon-client#9]
basically the same as 
https://github.com/janispritzkau/rcon-client/issues/5
but the reporter unfortunately did not tell HOW he fixed it
https://pastebin.com/MsAJcuRX

```
!!! ERROR !!! Error: connect ECONNREFUSED 127.0.0.1:25574
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1142:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 25574
}
```

**Comment by janispritzkau** [comment]
Hi, you should add a handler for the `error` event to prevent unexpected crashes. This is also the case with a lot of other node apis which will crash your node process if you haven't added a `error` event listener.

I've added a simple fix in 40e28c9. But I intend to further improve the error handling for this library.

**Comment by mindforger** [comment]
huh ?  thought i did here
```
          rcon.on("error", (err) => {
            this.events.push("!!!ERROR!!! "+ err);
          });
```

i am new to JS and TS so maybe i am missing the point you are telling me

**Comment by aldldl** [comment]
@janispritzkau I'm not crashing (thanks for the fix), but I cant seem to pull out the error .on("error") never pulls up for me when there is a server that is not on. I've tried a similar process as midforger did above and also had no luck catching the connection error.
